spring:
  data:
   redis:
     host: tiger-fly-ethereal-31105.db.redis.io
     port: 13799
     username: default
     password: 6H938B1CTcy9J2tk9JsMxo35KdZwQsnI
     mongodb:
       auto-index: true
       database: journalentdb
       uri: mongodb+srv://imkishanverma_db_user:ebkvam2iKpxa8Nox@cluster0.klby8uh.mongodb.net/?appName=Cluster0
  mail:
    host: smtp.gmail.com
    port: 587
    username: kishanberma7888@gmail.com
    password: vbhkxwkhydmoaoob
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
   name: mongo
server:
  port: 8081
#logging:
#  level:
#    com:
#      kishan:
#        mongo: DEBUG
# turn off everything only spring logo will be seen by below code
#logging:
#  level:
#    root: OFF
#logging:
#  level:
#    com:
#      kishan:
#        mongo: DEBUG
#        mongo.service.userService: OFF
# enable severity above debug.
logging:
  level:
    com.kishan.mongo: DEBUG
#    com.kishan.mongo.service.userService: OFF

weather:
  api:
    key: acab3c9b8f2146eda99183206260303